"""
Pydantic V2 Schemas for Project Apex.

Defines all structured data models used throughout the pipeline:
- AnomalyReport: Validated anomaly payload from BiLSTM → PydanticAI
- QueryContext: Database context for the reasoning agent
- OptimizationResult: Output from the SQL optimization agent
- IncidentRecord: Final record persisted to Supabase
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator


class AnomalyReport(BaseModel):
    """
    Validated anomaly report generated by the detection pipeline.

    Created by PydanticAI after receiving raw anomaly data from
    the BiLSTM detector and enriching it with database context.
    """

    anomaly_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for this anomaly instance",
    )
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="When the anomaly was detected",
    )
    severity: Literal["low", "medium", "high", "critical"] = Field(
        description="Severity level based on degradation factor"
    )
    anomaly_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Normalized anomaly score from BiLSTM (0-1)",
    )
    affected_query: str = Field(
        min_length=1,
        description="The SQL query causing the performance issue",
    )
    table_names: list[str] = Field(
        default_factory=list,
        description="Tables referenced in the affected query",
    )
    baseline_exec_ms: float = Field(
        ge=0.0,
        description="Normal (baseline) execution time in milliseconds",
    )
    current_exec_ms: float = Field(
        ge=0.0,
        description="Current (degraded) execution time in milliseconds",
    )
    degradation_factor: float = Field(
        ge=1.0,
        description="Ratio of current to baseline execution time",
    )
    source_metrics: dict[str, Any] = Field(
        default_factory=dict,
        description="Raw telemetry snapshot that triggered the anomaly",
    )

    @field_validator("degradation_factor", mode="before")
    @classmethod
    def compute_degradation(cls, v: float, info) -> float:
        """Auto-compute degradation factor if not provided."""
        if v is None or v < 1.0:
            baseline = info.data.get("baseline_exec_ms", 1.0)
            current = info.data.get("current_exec_ms", 1.0)
            return current / max(baseline, 0.001)
        return v


class QueryContext(BaseModel):
    """
    Database schema context provided to the reasoning agent.

    Contains the table schemas, indexes, and statistics needed
    for the LLM to understand the query optimization space.
    """

    database_name: str = Field(default="postgres")
    table_schemas: dict[str, list[dict[str, str]]] = Field(
        default_factory=dict,
        description="Table name → list of {column, type, nullable}",
    )
    existing_indexes: list[str] = Field(
        default_factory=list,
        description="CREATE INDEX statements for existing indexes",
    )
    table_statistics: dict[str, dict[str, Any]] = Field(
        default_factory=dict,
        description="Table name → row count, size, scan stats",
    )
    explain_plan: Optional[dict[str, Any]] = Field(
        default=None,
        description="EXPLAIN ANALYZE output for the affected query",
    )


class OptimizationResult(BaseModel):
    """
    Output from the SQL optimization reasoning agent.

    Contains the rewritten query, execution plan comparison,
    and index recommendations.
    """

    original_query: str = Field(description="The original slow query")
    optimized_query: str = Field(description="The optimized/rewritten query")
    optimization_reasoning: str = Field(
        default="",
        description="LLM's explanation of what was changed and why",
    )
    original_plan: dict[str, Any] = Field(
        default_factory=dict,
        description="EXPLAIN ANALYZE output for the original query",
    )
    optimized_plan: dict[str, Any] = Field(
        default_factory=dict,
        description="EXPLAIN ANALYZE output for the optimized query",
    )
    original_exec_ms: float = Field(
        default=0.0,
        description="Execution time of the original query",
    )
    optimized_exec_ms: float = Field(
        default=0.0,
        description="Execution time of the optimized query",
    )
    speedup_factor: float = Field(
        default=1.0,
        description="Original / Optimized execution time ratio",
    )
    index_recommendations: list[str] = Field(
        default_factory=list,
        description="Recommended CREATE INDEX statements",
    )
    status: Literal["improved", "no_change", "regression"] = Field(
        default="no_change",
        description="Whether the optimization improved performance",
    )

    @field_validator("speedup_factor", mode="before")
    @classmethod
    def compute_speedup(cls, v: float, info) -> float:
        """Auto-compute speedup factor."""
        if v is None or v <= 0:
            original = info.data.get("original_exec_ms", 1.0)
            optimized = info.data.get("optimized_exec_ms", 1.0)
            return original / max(optimized, 0.001)
        return v


class IncidentRecord(BaseModel):
    """
    Complete incident record for persistence and dashboard display.

    Combines the anomaly report and optimization result into a
    single record stored in the apex_incidents table.
    """

    incident_id: str = Field(default_factory=lambda: str(uuid4()))
    created_at: datetime = Field(default_factory=datetime.utcnow)
    resolved_at: Optional[datetime] = None
    severity: str
    anomaly_score: float
    affected_query: str
    table_names: list[str] = Field(default_factory=list)
    baseline_exec_ms: float
    current_exec_ms: float
    degradation_factor: float
    optimized_query: Optional[str] = None
    original_plan: dict[str, Any] = Field(default_factory=dict)
    optimized_plan: dict[str, Any] = Field(default_factory=dict)
    speedup_factor: Optional[float] = None
    index_recommendations: list[str] = Field(default_factory=list)
    resolution: Literal[
        "pending", "improved", "no_change", "escalated", "failed"
    ] = "pending"
    model_used: Optional[str] = None
    langgraph_thread_id: Optional[str] = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @classmethod
    def from_anomaly_and_result(
        cls,
        anomaly: AnomalyReport,
        result: Optional[OptimizationResult] = None,
        model_used: Optional[str] = None,
        thread_id: Optional[str] = None,
    ) -> IncidentRecord:
        """Create an incident record from an anomaly report and optional result."""
        record = cls(
            incident_id=anomaly.anomaly_id,
            created_at=anomaly.timestamp,
            severity=anomaly.severity,
            anomaly_score=anomaly.anomaly_score,
            affected_query=anomaly.affected_query,
            table_names=anomaly.table_names,
            baseline_exec_ms=anomaly.baseline_exec_ms,
            current_exec_ms=anomaly.current_exec_ms,
            degradation_factor=anomaly.degradation_factor,
            model_used=model_used,
            langgraph_thread_id=thread_id,
        )

        if result:
            record.optimized_query = result.optimized_query
            record.original_plan = result.original_plan
            record.optimized_plan = result.optimized_plan
            record.speedup_factor = result.speedup_factor
            record.index_recommendations = result.index_recommendations
            record.resolution = result.status
            record.resolved_at = datetime.utcnow()

        return record
